FROM alpine:3.20

ENV PATH="/usr/share/perl6/site/bin:$PATH"

 ARG rakudo=main

 # Leave git installed for zef.
 RUN apk add --no-cache gcc git linux-headers make musl-dev perl openssl-dev
 RUN git clone -b $rakudo https://github.com/rakudo/rakudo       \
  && cd rakudo                                                   \
  && CFLAGS=-flto ./Configure.pl                                 \
     --gen-moar                                                  \
     --moar-option=--ar=gcc-ar                                   \
     --prefix=/usr                                               \
  && make install                                                \
  && strip /usr/lib/libmoar.so                                   \
  && cd /                                                        \
  && rm -rf rakudo

 ARG getopt=0.4.2
 ARG prove6=0.0.17
 ARG tap=0.3.14
 ARG zef=v0.22.5

 RUN git clone -b $zef https://github.com/ugexe/zef        \
  && perl6 -Izef/lib zef/bin/zef --/test install ./zef     \
     $([ -z $getopt ] || echo "Getopt::Long:ver<$getopt>") \
     $([ -z $prove6 ] || echo "App::Prove6:ver<$prove6>" ) \
     $([ -z $tap    ] || echo "TAP:ver<$tap>"            ) \
  && rm -rf zef

RUN zef install 'Cro::Core'
RUN zef install --/test 'Cro::HTTP'
RUN zef install --/test 'Cro::WebSocket'

# remove unneeded dependents
RUN apk del gcc linux-headers make musl-dev perl
RUN mkdir /app
COPY service.raku /app
WORKDIR /app
EXPOSE 40005
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser
CMD raku service.raku
